name: workfina
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  flutter_secure_storage: ^10.0.0
  dio: ^5.9.0
  file_picker: ^10.3.8
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  google_nav_bar: ^5.0.7
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  intl: ^0.20.2
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  package_info_plus: ^8.0.0
  video_thumbnail: ^0.5.6
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/workfina1.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/svg/
    - assets/logos/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
